/**
 * Sistema de diseño "NovaDesk AI" — extraído literalmente de las pantallas exportadas
 * desde Stitch (paleta pizarra/gris + acentos índigo/violeta para funciones de IA).
 * No modificar valores individuales sin actualizar también las plantillas: todas las
 * pantallas comparten este mismo token set.
 */
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-variant': '#d3e4fe',
        'inverse-primary': '#c3c0ff',
        'secondary-fixed': '#eaddff',
        'surface-container-low': '#eff4ff',
        'ai-purple': '#8b5cf6',
        'on-secondary-fixed': '#25005a',
        'surface-tint': '#4d44e3',
        'tertiary-fixed': '#c9e6ff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'status-resolved': '#10b981',
        'on-surface': '#0b1c30',
        'surface-canvas': '#f8fafc',
        'error-container': '#ffdad6',
        'surface-elevated': '#f1f5f9',
        'on-tertiary-fixed': '#001e2f',
        'tertiary-fixed-dim': '#89ceff',
        'on-error': '#ffffff',
        'secondary-container': '#8a4cfc',
        'primary-container': '#4f46e5',
        'status-incident-bg': '#fff1f2',
        error: '#ba1a1a',
        'surface-dim': '#cbdbf5',
        'primary-fixed-dim': '#c3c0ff',
        background: '#f8f9ff',
        outline: '#777587',
        'on-primary-fixed': '#0f0069',
        'on-tertiary-container': '#b8e0ff',
        tertiary: '#004d70',
        'status-incident': '#f43f5e',
        'primary-fixed': '#e2dfff',
        surface: '#f8f9ff',
        'on-primary-container': '#dad7ff',
        'surface-container-highest': '#d3e4fe',
        'surface-container-high': '#dce9ff',
        'surface-bright': '#f8f9ff',
        'on-secondary-container': '#fffbff',
        'tertiary-container': '#006693',
        'on-background': '#0b1c30',
        'surface-card': '#ffffff',
        'inverse-surface': '#213145',
        secondary: '#712ae2',
        'outline-variant': '#c7c4d8',
        'surface-container': '#e5eeff',
        'border-strong': '#cbd5e1',
        'secondary-fixed-dim': '#d2bbff',
        'inverse-on-surface': '#eaf1ff',
        'ai-purple-subtle': '#f5f3ff',
        'on-error-container': '#93000a',
        'on-primary-fixed-variant': '#3323cc',
        'status-warning': '#f59e0b',
        'on-surface-variant': '#464555',
        'border-subtle': '#e2e8f0',
        primary: '#3525cd',
        'status-resolved-bg': '#ecfdf5',
        'on-tertiary-fixed-variant': '#004c6e',
        'status-warning-bg': '#fffbeb',
        'on-secondary-fixed-variant': '#5a00c6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-lg': '1rem',
        gutter: '1rem',
        'space-xl': '1.5rem',
        'space-2xs': '0.125rem',
        'space-sm': '0.5rem',
        margin: '1.5rem',
        'space-xs': '0.25rem',
        'margin-compact': '1rem',
        'space-md': '0.75rem',
        'space-2xl': '2rem',
        'gutter-compact': '0.75rem',
      },
      fontFamily: {
        'label-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'code-mono': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'code-mono': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        display: ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-lg': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'body-lg': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
